import { Dimensions, StyleSheet } from "react-native";
import Colors from './Colors'

const { width, height } = Dimensions.get('window');
const fontFamily = 'open-sans';
const fontFamilyBold = 'open-sans-bold';

const Styles = StyleSheet.create({
  fontFamily: { fontFamily },
  fontFamilyBold: { fontFamily: fontFamilyBold },

  margin0: { margin: 0 },
  margin5: { margin: 5 },
  marginT0: { marginTop: 0 },
  marginT5: { marginTop: 5 },
  marginB5: { marginBottom: 5 },
  marginL5: { marginLeft: 5 },
  marginR5: { marginRight: 5 },
  margin10: { margin: 10 },
  marginT10: { marginTop: 10 },
  marginB10: { marginBottom: 10 },
  marginL10: { marginLeft: 10 },
  marginR10: { marginRight: 10 },
  margin15: { margin: 15 },
  marginT15: { marginTop: 15 },
  marginB15: { marginBottom: 15 },
  marginL15: { marginLeft: 15 },
  marginR15: { marginRight: 15 },
  margin20: { margin: 20 },
  marginT20: { marginTop: 20 },
  marginB20: { marginBottom: 20 },
  marginL20: { marginLeft: 20 },
  marginR20: { marginRight: 20 },
  padding0: { padding: 0 },
  paddingT0: { paddingTop: 0 },
  paddingB0: { paddingBottom: 0 },
  paddingL0: { paddingLeft: 0 },
  paddingR0: { paddingRight: 0 },
  padding5: { padding: 5 },
  paddingT5: { paddingTop: 5 },
  paddingB5: { paddingBottom: 5 },
  paddingL5: { paddingLeft: 5 },
  paddingR5: { paddingRight: 5 },
  padding10: { padding: 10 },
  paddingT10: { paddingTop: 10 },
  paddingB10: { paddingBottom: 10 },
  paddingL10: { paddingLeft: 10 },
  paddingR10: { paddingRight: 10 },
  padding15: { padding: 15 },
  paddingT15: { paddingTop: 15 },
  paddingB15: { paddingBottom: 15 },
  paddingL15: { paddingLeft: 15 },
  paddingR15: { paddingRight: 15 },
  padding20: { padding: 20 },
  paddingT20: { paddingTop: 20 },
  paddingB20: { paddingBottom: 20 },
  paddingL20: { paddingLeft: 20 },
  paddingR20: { paddingRight: 20 },

  textDefault: { fontFamily, color: Colors.defaultText },
  text10: { fontFamily, fontSize: 10, color: Colors.defaultText },
  text12: { fontFamily, fontSize: 12, color: Colors.defaultText },
  text13: { fontFamily, fontSize: 13, color: Colors.defaultText },
  text14: { fontFamily, fontSize: 14, color: Colors.defaultText },
  text15: { fontFamily, fontSize: 15, color: Colors.defaultText },
  text16: { fontFamily, fontSize: 16, color: Colors.defaultText },
  text17: { fontFamily, fontSize: 17, color: Colors.defaultText },
  text18: { fontFamily, fontSize: 18, color: Colors.defaultText },
  text20: { fontFamily, fontSize: 20, color: Colors.defaultText },
  text22: { fontFamily, fontSize: 22, color: Colors.defaultText },
  text24: { fontFamily, fontSize: 24, color: Colors.defaultText },
  text26: { fontFamily, fontSize: 26, color: Colors.defaultText },
  text28: { fontFamily, fontSize: 28, color: Colors.defaultText },
  text35: { fontFamily, fontSize: 35, color: Colors.defaultText },
  text40: { fontFamily, fontSize: 40, color: Colors.defaultText },
  textBold: { fontFamily: fontFamilyBold, color: Colors.defaultText },
  textCenter: { textAlign: 'center' },
  textJustify: { textAlign: 'justify' },
  textWhite: { color: 'white' },
  textOrange: { color: Colors.primaryColor },
  textLightText: { color: Colors.lightText },
  textRed: { color: Colors.red },
  textEmpty: { fontFamily, fontSize: 14, color: Colors.lightText, textAlign: 'center' },

  marker: { fontSize: 15, fontFamily: fontFamilyBold, color: Colors.primaryColor },
  boxMarker: { fontSize: 15, fontFamily: fontFamilyBold, textAlign: 'center', paddingLeft: 5, paddingRight: 5, backgroundColor: Colors.primaryColor, borderRadius: 4, color: 'white' },
  articleIcon: { fontFamily, fontSize: 25 },
  menuIcon: { fontFamily, fontSize: 26 },
  avatarSettings: { height: 120 },

  menuStyleContainer: { padding: 15, paddingLeft: 10, paddingRight: 10 },
  menuStyleHeader: { height: 80 },
  menuStyleCompanyIcon: { maxHeight: 30, resizeMode: 'contain' },
  menuStyleItem: { flex: 1, width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start', paddingBottom: 15 },
  menuStyleItemText: { fontFamily, fontSize: 16, color: Colors.defaultText },
  menuStyleItemIcon: { width: 50, textAlign: 'center' },
  headerTitleStyle: { fontFamily: fontFamilyBold, color: Colors.defaultText, fontSize: 17 },

  btnOrange: { borderWidth: 1, borderColor: Colors.primaryColor, backgroundColor: Colors.primaryColor },
  btnBorderWhite: { borderWidth: 1, borderColor: 'white' },
  btnBorder: { borderWidth: 1, borderColor: Colors.primaryColor },
  btnBorderRed: { borderWidth: 1, borderColor: Colors.red },
  btnBorderGreen: { borderWidth: 1, borderColor: Colors.green },
  btnBorderDF: { borderWidth: 1, borderColor: Colors.defaultText },
  btnBorderLF: { borderWidth: 1, borderColor: Colors.lightText },
  btnBorderLG: { borderWidth: 1, borderColor: Colors.lightGray },
  btnDialogAction: { borderColor: Colors.lightText, borderRadius: 20, borderWidth: 1, paddingVertical: 3, paddingHorizontal: 6, alignItems: 'center', marginRight: 4 },
  btnFloatAdd: { alignItems: 'center', justifyContent: 'center', width: 60, height: 60, borderRadius: 30, backgroundColor: Colors.primaryColor, position: 'absolute', bottom: 10, right: 10 },
  btnFloatAddIcon: { fontFamily, fontSize: 30 },
  
  statusLock: { paddingVertical: 3, paddingHorizontal: 6, alignItems: 'center' },
  inputLogin: { color: Colors.defaultText, borderWidth: 1, borderColor: Colors.primaryColor, paddingHorizontal: 15, paddingVertical: 5, fontFamily: fontFamilyBold, borderRadius: 4 },
  inputLoginView: { width: '100%', borderWidth: 1, borderRadius: 20, borderColor: Colors.primaryColor },
  inputReflection: { borderColor: Colors.gray, borderWidth: StyleSheet.hairlineWidth, color: Colors.defaultText, padding: 10, paddingVertical: 5, fontSize: 17, height: height*0.2 },
  inputSearch: { borderBottomColor: Colors.lightGray, borderBottomWidth: StyleSheet.hairlineWidth, color: Colors.defaultText, fontSize: 17, fontFamily },
  inputComment: { width: '85%', minHeight: 40, maxHeight: 80, fontFamily, fontSize: 15, color: Colors.defaultText, paddingHorizontal: 10, paddingVertical: 5 },
  picker: { height: 35, width: '100%', fontFamily, fontSize: 15, padding: 0, borderBottomColor: Colors.lightText, borderBottomWidth: StyleSheet.hairlineWidth, color: Colors.defaultText },

  center: { alignItems: 'center', justifyContent: 'center' },
  viewCenter: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  inline: { flexDirection: 'row', flexWrap: 'wrap' },
  container: { flex: 1, padding: 10 },
  card: { margin: 0, padding: 10, backgroundColor: 'white', borderWidth: 0, borderRadius: 4 },
  cardRounded: { margin: 0, backgroundColor: 'white', borderWidth: 0, borderRadius: 4, padding: 10, paddingHorizontal: 15 },
  cardContainer: { padding: 10, margin: 0 },
  homeCardIcon: { height: 70, resizeMode: 'contain', margin: 0 },
  borderTopTest: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: Colors.lightText },
  privPub: { borderColor: Colors.primaryColor, borderRadius: 20, borderWidth: 1, paddingVertical: 4, alignItems: 'center' },
  borderTopSlim: { borderTopColor: Colors.lightText, borderTopWidth: StyleSheet.hairlineWidth },

  modalHeaderArticle: { position: 'relative', paddingHorizontal: 0, paddingVertical: 15, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#d0d0d0' },
  modalHeader: { position: 'relative', paddingHorizontal: 20, paddingVertical: 15, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#d0d0d0' },
  modalContainer: { paddingHorizontal: 10, paddingVertical: 5 },

  cardOverlay: { paddingHorizontal: 15, paddingVertical: 10, marginHorizontal: 15, marginVertical: 5, backgroundColor: 'white', borderRadius: 4 },
  cardSettings: { paddingHorizontal: 10, paddingVertical: 5, marginHorizontal: 15, backgroundColor: 'white', borderRadius: 4 },
  cardUser: { backgroundColor: 'white', borderRadius: 4 },
  inputDate: { fontFamily, fontSize: 15, padding: 5, borderBottomColor: Colors.lightText, borderBottomWidth: StyleSheet.hairlineWidth, color: Colors.defaultText },
  inputTopic: { fontFamily, fontSize: 15, padding: 0, paddingBottom: 5, paddingTop: 5, borderBottomColor: Colors.lightText, borderBottomWidth: StyleSheet.hairlineWidth, color: Colors.defaultText },
  inputUser: { fontFamily, fontSize: 15, padding: 0, paddingBottom: 2, paddingTop: 0, borderBottomColor: Colors.lightText, borderBottomWidth: StyleSheet.hairlineWidth, color: Colors.defaultText },
  inputDialogText: { fontFamily, fontSize: 15, padding: 0, paddingBottom: 5, paddingTop: 5, borderBottomColor: Colors.lightText, borderBottomWidth: StyleSheet.hairlineWidth, color: Colors.defaultText, maxHeight: height*0.3 },
  btnBorderRounded: { borderRadius: 20 },
  border: { borderColor: Colors.lightGray, borderWidth: StyleSheet.hairlineWidth },
  topBorder: { borderTopColor: Colors.lightGray, borderTopWidth: StyleSheet.hairlineWidth },
  bottomBorderLT: { borderBottomColor: Colors.lightText, borderBottomWidth: StyleSheet.hairlineWidth },
  bottomBorder: { borderBottomColor: Colors.lightGray, borderBottomWidth: StyleSheet.hairlineWidth },
  input: { color: Colors.defaultText, padding: 5, paddingLeft: 0, paddingRight: 0 },
  inputRegister: { color: Colors.defaultText, padding: 5, paddingLeft: 0, paddingRight: 0, borderBottomColor: 'white', borderBottomWidth: StyleSheet.hairlineWidth },

  trackBottom: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', padding: 10, height: 60 },
  trackTestFinishButtons: { width: width*0.4, borderWidth: 1, borderColor: Colors.lightText, padding: 10, borderRadius: 4 },

  spaceAround: { justifyContent: 'space-around' },
  spaceBetween: { justifyContent: 'space-between' },

  textAreaView: { borderColor: '#aaa', borderWidth: 1, padding: 5, marginTop: 10 },
  textArea: { height: 120, justifyContent: "flex-start", color: Colors.lightText, textAlignVertical: 'top', fontFamily, fontSize: 15 },
  viewDivider15: { height: 15 },
  viewDivider: { height: 10 },
  viewDividerLine: { height: StyleSheet.hairlineWidth, width: '100%', borderBottomColor: Colors.lightGray, borderBottomWidth: StyleSheet.hairlineWidth }
});

export default Styles;
